// <auto-generated />
using System;
using ASP.NET_TEST.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_TEST.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404161359_AddSeedingDataDiaryEntry")]
    partial class AddSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_TEST.Models.DiaryEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "Went Hiking with Denis",
                            Created = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Hiking"
                        },
                        new
                        {
                            ID = 2,
                            Content = "Went Hiking with Alisson",
                            Created = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Hiking"
                        },
                        new
                        {
                            ID = 3,
                            Content = "Went Biking with Alisson",
                            Created = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Biking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
